<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsTestProject>true</IsTestProject>
    <IsPackable>false</IsPackable>
    <AssemblyName>AEVRIX.Remote.Security.Tests</AssemblyName>
    <RootNamespace>Aevrix.Remote.Security.Tests</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.8.1" />
    <PackageReference Include="MSTest" Version="4.3.2" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\AEVRIX.Remote.Security\AEVRIX.Remote.Security.csproj" />
  </ItemGroup>
</Project>
