<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>AEVRIX.EngineHost</AssemblyName>
    <RootNamespace>Aevrix.EngineHost</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\AEVRIX.Core\AEVRIX.Core.csproj" />
  </ItemGroup>
</Project>
